name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - if: ${{ startsWith(matrix.os, 'windows') }}
      name: Install cmfrec.dll
      run: |
        mkdir /build
        cd /build
        curl -Ls -o libblas.lib https://icl.cs.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win64/libblas.lib
        curl -Ls -o liblapack.lib https://icl.cs.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win64/liblapack.lib
    - if: ${{ startsWith(matrix.os, 'windows') }}
      name: Install cmfrec.dll, part 2
      run: |
        git clone --recursive --branch master https://github.com/david-cortes/cmfrec.git
        cd cmfrec
        git checkout d9e69573d22ab496e34cd7846082b40554dc7b4b
        mkdir build
        cd build
        cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release -DBLAS_LIBRARIES=/build/libblas.lib -DLAPACK_LIBRARIES=/build/liblapack.lib
        cmake --build . --config Release
        cp Release/cmfrec.dll ../../vendor
      shell: cmd
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - if: ${{ !startsWith(matrix.os, 'windows') }}
      run: bundle exec rake vendor:all
    - run: bundle exec rake test
